src/Entity/Funcionario.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\FuncionarioRepository")
 */
class Funcionario
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     *
     */
    private $id;

    /** @var Secretaria
     * @ORM\ManyToOne(targetEntity="App\Entity\Secretaria")
     * @Assert\NotBlank()
     */
    private $secretaria;

    /**
     * @var string
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     */
    private $nome;

    /**
     * @var integer
     * @ORM\Column(type="integer")
     * @Assert\Notblank()
     * @Assert\Range(min="0", max="70")
     */
    private $idade;

    /**
     * @var string
     * @ORM\Column(type="string", length=1)
     * @Assert\Choice(choices={"M","F"})
     */
    private $sexo;

    /**
     * @var \DateTime
     * @ORM\Column(type="date")
     * @Assert\NotBlank()
     * @Assert\Date()
     */
    private $data_nascimento;

    /**
     * @var Endereco
     * @ORM\ManyToOne(targetEntity="App\Entity\Endereco", cascade={"persist"})
     * @Assert\Valid()
     */
    private $endereco;

    /**
     * @var string
     * @ORM\Column(type="string", length=16, unique=true)
     * @Assert\NotBlank(message="O campo nome não pode ser vazio!")
     */
    private $cpf;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\File(mimeTypes={"application/pdf"}, mimeTypesMessage="arquivo invalido")
     * @Assert\NotBlank(message = "selecione um pdf para esse campo")
     */
    private $imagem_documento;

    /**
     * @var string
     * @ORM\Column(type="string", length=14)
     * @Assert\Notblank()
     * @Assert\Choice(choices={"Efetivo", "Comissionado"})
     */
    private $cargo;

    /** @var \Date
     * @ORM\Column(type="date")
     * @Assert\Date()
     * @Assert\Notblank()
     *
     */
    private $data_admissao;

    /**
     * @var \Date
     * @ORM\Column(type="date", nullable=true)
     * @Assert\Date()
     * @Assert\Expression(
     *     "this.getStatus() == 'A' && value == '' || this.getStatus() == 'E' && value != '' ",
     *     message=" verificar o campo."
     *)
     */
    private $data_exoneracao;

    /**
     * @var string
     * @ORM\Column(type="string", length=1)
     * @Assert\Choice(choices={"A", "E"})
     */
    private $status = "A";

    /** @var float
     * @ORM\Column(type="decimal", precision=10, scale=2)
     * @Assert\NotBlank()
     * @Assert\Range(min="0", max="100000")
     */
    private $sal_base;

    /**
     * @var float
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     * @Assert\Range(min="0", max="100000")
     * @Assert\Expression(
     *     "this.getCargo() == 'Comissionado' && value == '' || this.getCargo() == 'Efetivo' && value != '' ",
     *    message="não preencher")
     */
    private $gratif;

    /**
     * @var float
     * @ORM\Column(type="decimal", precision=10, scale=2)
     * @Assert\NotBlank()
     * @Assert\Range(min="0", max="100000")
     *
     */
    private $desconto;

    /** @var float
     * @ORM\Column(type="decimal", precision=10, scale=2)
     * @Assert\Range(min="0", max="100000")
     */
    private $liquido;

    public function calculoLiquido()
    {
        $result_liquido = ($this->getSalBase() + $this->getGratif()) - $this->getDesconto();
        $this->setLiquido($result_liquido);
    }


    public function getId()
    {
        return $this->id;
    }


    public function getSecretaria()
    {
        return $this->secretaria;
    }


    public function setSecretaria($secretaria)
    {
        $this->secretaria = $secretaria;
        return $this;
    }

    public function getNome()
    {
        return $this->nome;
    }


    public function setNome($nome)
    {
        $this->nome = $nome;
        return $this;
    }


    public function getIdade()
    {
        return $this->idade;
    }


    public function setIdade($idade)
    {
        $this->idade = $idade;
        return $this;
    }


    public function getSexo()
    {
        return $this->sexo;
    }


    public function setSexo($sexo)
    {
        $this->sexo = $sexo;
        return $this;
    }


    public function getDataNascimento()
    {
        return $this->data_nascimento;
    }


    public function setDataNascimento($data_nascimento)
    {
        $this->data_nascimento = $data_nascimento;
        return $this;
    }


    public function getEndereco()
    {
        return $this->endereco;
    }


    public function setEndereco($endereco)
    {
        $this->endereco = $endereco;
        return $this;
    }


    public function getCpf()
    {
        return $this->cpf;
    }


    public function setCpf($cpf)
    {
        $this->cpf = $cpf;
        return $this;
    }

    /**
     * @return string
     */
    public function getImagemDocumento()
    {
        return $this->imagem_documento;
    }

    /**
     * @param string $imagem_documento
     * @return Funcionario
     */
    public function setImagemDocumento($imagem_documento)
    {
        $this->imagem_documento = $imagem_documento;
        return $this;
    }

    public function getCargo()
    {
        return $this->cargo;
    }


    public function setCargo($cargo)
    {
        $this->cargo = $cargo;
        return $this;
    }


    public function getDataAdmissao()
    {
        return $this->data_admissao;
    }


    public function setDataAdmissao($data_admissao)
    {
        $this->data_admissao = $data_admissao;
        return $this;
    }


    public function getDataExoneracao()
    {
        return $this->data_exoneracao;
    }


    public function setDataExoneracao($data_exoneracao)
    {
        $this->data_exoneracao = $data_exoneracao;
        return $this;
    }


    public function getStatus()
    {
        return $this->status;
    }


    public function setStatus($status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return float
     */
    public function getSalBase()
    {
        return $this->sal_base;
    }

    /**
     * @param float $sal_base
     * @return Funcionario
     */
    public function setSalBase(float $sal_base): Funcionario
    {
        $this->sal_base = $sal_base;
        return $this;
    }

    /**
     * @return float
     */
    public function getGratif()
    {
        return $this->gratif;
    }

    /**
     * @param float $gratif
     * @return Funcionario
     */
    public function setGratif(?float $gratif): Funcionario
    {
        $this->gratif = $gratif;
        return $this;
    }

    /**
     * @return float
     */
    public function getDesconto()
    {
        return $this->desconto;
    }

    /**
     * @param float $desconto
     * @return Funcionario
     */
    public function setDesconto(float $desconto): Funcionario
    {
        $this->desconto = $desconto;
        return $this;
    }

    /**
     * @return float
     */
    public function getLiquido()
    {
        return $this->liquido;
    }

    /**
     * @param float $liquido
     * @return Funcionario
     */
    public function setLiquido(float $liquido): Funcionario
    {
        $this->liquido = $liquido;
        return $this;
    }

}

src/Form/RelatorioType.php
<?php

namespace App\Form;

use App\Entity\Funcionario;
use App\Enum\FuncionarioStatusEnum;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RelatorioType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('data_inicio', DateType::class, [
                'widget' => 'single_text',

            ])
            ->add('data_fim', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('status', ChoiceType::class, [
                'choices' => array_flip(FuncionarioStatusEnum::getStatus())
            ])
            ->add('pdf', SubmitType::class, [
                'label' => 'Gerar PDF'
            ])
            ->add('excel', SubmitType::class, [
                'label' => 'Gerar excel'
            ])
            ->add('pesquisar', SubmitType::class, [
                'label' => 'Pesquisar'
            ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/RelatorioController.php
<?php

namespace App\Controller;

use App\Entity\Secretaria;
use App\Enum\FuncionarioStatusEnum;
use App\Form\RelatorioSecretariaType;
use App\Form\RelatorioType;
use App\Repository\FuncionarioRepository;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Dompdf\Dompdf;


require __DIR__ . '/../../vendor/autoload.php';


class RelatorioController extends Controller
{
    /**
     * @Route("/relatorio", name="relatorio")
     */
    public function index()
    {
        return $this->render('relatorio/index.html.twig', [
            'controller_name' => 'RelatorioController',
        ]);
    }

    /**
     * @param Request $request
     * @Route("/relatorio/funcional", name="relatorio_funcionario")
     * @return Response
     */
    public function relatorioFuncionario(Request $request, FuncionarioRepository $funcionarioRepository)
    {

        $funcionarios = [];
        $form = $this->createForm(RelatorioType::class, $funcionarios);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $funcionarios = $funcionarioRepository->getFuncionarioPorData(
                $data['data_inicio'],
                $data['data_fim'],
                $data['status']
            );

            $pdfClicked = $form->get('pdf')->isClicked();

            if ($pdfClicked) {
                return $this->funcionarioPdf($funcionarios);
            }

            $excelClicked = $form->get('excel')->isClicked();

            if ($excelClicked) {
                $plan = $this->funcionarioXls($funcionarios);

                return new Response(
                    $plan, 200,
                    array(
                        'Content-Type' => 'application/vnd.ms-excel',
                        'Content-Disposition'
                        => 'attachment; filename="myfile.xlsx"',
                    )
                );

            }

        }

        return $this->render('relatorio/funcional.html.twig',
            ['funcionarios' => $funcionarios,
                'form' => $form->createView()]
        );
    }

    /**
     * @param $funcionarios
     * @return mixed
     * @Route ("relatorio/funcional_pdf" , name="funcionario_pdf")
     * @Template ("relatorio/funcional_pdf.html.twig")
     */
    private function funcionarioPdf($funcionarios)
    {
        $view = $this->renderView('relatorio/funcional_pdf.html.twig', [
            'funcionarios' => $funcionarios
        ]);

        $domPdf = new Dompdf();
        $domPdf->loadHtml($view);
        $domPdf->setPaper('A4', 'portrait');
        $domPdf->render();
        return $domPdf->stream('relatorio_funcionario');
    }

    /**
     * @Route("/relatorio/funcional_xls", name="relatorio_xls")
     *
     */
    private function funcionarioXls($funcionarios)
    {
        $spreadsheet = new Spreadsheet(); //instanciando uma nova planilha

        $total = $funcionarios;

        $plan = $spreadsheet->getActiveSheet(); //retornando a aba ativa

        $plan->setCellValue('A1', 'Mat.');
        $plan->setCellValue('B1', 'Nome');
        $plan->setCellValue('C1', 'Cargo');
        $plan->setCellValue('D1', 'Status');
        $plan->setCellValue('E1', 'Data de admissao');
        $plan->setCellValue('F1', 'Data de exoneração');

        $contador = 1;

        foreach ($total as $linha) {

            $contador++;

            $plan->setCellValue('A' . $contador, $linha->getId());
            $plan->setCellValue('B' . $contador, $linha->getNome());
            $plan->setCellValue('C' . $contador, $linha->getCargo());
            $plan->setCellValue('D' . $contador, $linha->getStatus());
            $plan->setCellValue('E' . $contador, $linha->getDataAdmissao());
            $plan->setCellValue('F' . $contador, $linha->getDataExoneracao());

        }

        $writer = new Xlsx ($spreadsheet);
        ob_start();
        $writer->save('php://output');
        return ob_get_clean();
    }

    /**
     * @param Request $request
     *
     * @Route("/relatorio/secretaria",name="relatorio_secretaria")
     * @Template("relatorio/secretaria.html.twig")
     * @return Response
     */
    public function relatorioSecretaria(Request $request, FuncionarioRepository $funcionarioRepository)
    {
        return $this->render(
            'relatorio/secretaria.html.twig',
            ['totalSalariosLiquido' => $funcionarioRepository->salarioTotal()]
        );
    }

    /**
     * @Route("/relatorio/secretaria_pdf", name="secretaria_pdf")
     */
    public function secretariaPdf(Request $request, FuncionarioRepository $funcionarioRepository)
    {

        $view = $this->renderView(
            'relatorio/secretaria_pdf.html.twig',
            ['totalSalariosLiquido' => $funcionarioRepository->salarioTotal()]
        );
        $domPdf = new Dompdf();
        $domPdf->loadHtml($view);
        $domPdf->setPaper('A4', 'portrait');
        $domPdf->render();
        return $domPdf->stream("Relatório_Secretaria.pdf");
    }

}

templates/relatorio/funcional.html.twig
{% extends 'base.html.twig' %}

{% block title %}Relatórios - {% endblock %}

{% block body %}
    <h1>Relatório de Funcionários</h1>
    <main class="container mt-5">
        {% form_theme form with 'bootstrap_4_layout.html.twig' %}
        {{ form_start(form, {"attr":{"novalidate":"novalidate"}}) }}
        {{ form_widget(form) }}
        <br>
        {{ form_end(form) }}

        <table class="table">
            <thead>
            <tr>
                <th>Mat.</th>
                <th>Nome</th>
                <th>Cargo</th>
                <th>Status</th>
                <th>Data de admissão</th>
                <th>Data de exoneração</th>
            </tr>
            </thead>
            <tbody>
            {% for funcionario in funcionarios %}
                <tr>
                    <td>{{ funcionario.id }}</td>
                    <td>{{ funcionario.nome }}</td>
                    <td> {% if funcionario.cargo == "Comissionado" %}
                            <p>Comissionado</p>
                        {% elseif funcionario.cargo == "Efetivo" %}
                            <p>Efetivo</p>
                        {% endif %}
                    </td>
                    <td> {% if funcionario.status == "A" %}
                            <p>Ativo</p>
                        {% elseif funcionario.status == "E" %}
                            <p>Exonerado</p>
                        {% endif %}</td>
                    <td>{{ funcionario.dataAdmissao|date('d/m/Y') }}</td>
                    <td>{{ funcionario.dataExoneracao == '' ? '' : funcionario.dataExoneracao|date('d/m/Y') }}</td>


                </tr>
            {% else %}
                <tr>
                    <td colspan="18">no records found</td>
                </tr>

            {% endfor %}
            </tbody>
            <tr>
            </tr>
        </table>

        <a href='{{ path('relatorio') }}' class="btn btn-primary btn-sm">Voltar</a>

    </main>
{% endblock %}

templates/relatorio/funcional_pdf.html.twig
<h1 class="display-3">Relatório de Funcionarios</h1>
<br>
<table class=" table table-striped table-hover xmlns= http://www.w3.org/1999/html">
<tbody>
<thead>
<tr>
    <th>Mat.</th>
    <th>Nome</th>
    <th>Cargo</th>
    <th>Status</th>
    <th>Data de admissão</th>
    <th>Data de exoneração</th>
</tr>
</thead>
</tbody>

</tbody>
{% for funcionario in funcionarios %}
    <tr>
        <td>{{ funcionario.id }}</td>
        <td>{{ funcionario.nome }}</td>
        <td> {% if funcionario.cargo == "C" %}
                <p>Comissionado</p>
            {% elseif funcionario.cargo == "E" %}
                <p>Efetivo</p>
            {% endif %}
        </td>
        <td> {% if funcionario.status == "A" %}
                <p>Ativo</p>
            {% elseif funcionario.status == "E" %}
                <p>Exonerado</p>
            {% endif %}</td>
        <td>{{ funcionario.dataAdmissao|date('d/m/Y') }}</td>
        <td>{{ funcionario.dataExoneracao == '' ? '' : funcionario.dataExoneracao|date('d/m/Y') }}</td>

    </tr>
{% else %}
    <tr>
        <td colspan="18">no records found</td>
    </tr>
    </tbody>
</table>
{% endfor %}

templates/relatorio/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Relatorio {% endblock %}

{% block body %}
    <h1 class="display-3">Relatórios</h1>
    <table class="table table-striped table-hover">
        <br>
        <tbody>
        <thead>
        <tr>
            <th> Período por Admissão/Exoneração <a href="{{ path('relatorio_funcionario') }}" class="btn btn-primary">Gerar
                    relatório</a>
            </th>
            <th> Total de Salário Líquido por Secretaria <a href="{{ path('relatorio_secretaria') }}"
                                                            class="btn btn-primary">Gerar
                    relatório</a>
            </th>
        </tr>
        </thead>
        </tbody>
    </table>
{% endblock %}

templates/relatorio/secretaria.html.twig
{% extends 'base.html.twig' %}

{% block title %}Relatórios - {% endblock %}

{% block body %}

    <h1>Relatório de Secretarias</h1>
    <br>

    <table class="table">
        <thead>
        <tr>
            <th>Total de Salário</th>
            <th>Secretaria</th>
        </tr>
        </thead>
        <tbody>
        {% for totalSalarioLiquido in totalSalariosLiquido %}
            <tr>
                <td>{{ totalSalarioLiquido.total|number_format(2, ',', '.') }}</td>
                <td>{{ totalSalarioLiquido.nome }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="18">no records found</td>
            </tr>

        {% endfor %}
        </tbody>
    </table>
    <div class="row">
        <div class="form-group col-12">
            <a href='{{ path('secretaria_pdf') }}' class="btn btn-primary btn-sm">Gerar PDF</a>
        </div>
    </div>
    <a href='{{ path('relatorio') }}' class="btn btn-primary btn-sm">Voltar</a>


{% endblock %}

templates/relatorio/secretaria_pdf.html.twig
<h1>Relatório de Secretarias</h1>

<table id="customers">

    <thead>
    <tr>
        <th>Total de Salário</th>
        <th>Secretaria</th>
    </tr>
    </thead>
    <tbody>
    {% for totalSalarioLiquido in totalSalariosLiquido %}
        <tr>
            <td> R$ {{ totalSalarioLiquido.total|number_format(2, ',', '.') }}</td>
            <td>{{ totalSalarioLiquido.nome }}</td>
        </tr>
    {% else %}
        <tr>
            <td colspan="18">relatório não encontrado</td>
        </tr>
    {% endfor %}
    </tbody>
</table